version: "2"
services:
  web:
    build: .
    hostname: git
    domainname: example.com
    ports:
      - "10080:80"
      - "9418:9418"
    volumes:
      - "/Users/harre/hoge:/srv/repositories:ro"
    tmpfs:
      - /run
