version: "2"
services:
  web:
    build: .
    hostname: git
    domainname: example.com
    ports:
      - "80:80"
    volumes:
      - "/srv/repositories:/srv/repositories:ro"
    tmpfs:
      - /run
